name: PreRelease

on:
    push:
        branches:
            - prerelease

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Init pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 7.16.1

            - name: Init node
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
                  registry-url: https://registry.npmjs.org/
                  cache: pnpm

            - run: pnpm install

            - run: pnpm build

            - name: Publish
              run: pnpm --no-git-checks -r publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}